-- Magnitude Analysis 
-- Magnitude = Aggregation of Measure by Dimension.
-- Example:  Total sales by category 

SELECT * FROM gold.dim_customers;

-- Find total customers by countries 
SELECT  country, COUNT(DISTINCT customer_key)
FROM gold.dim_customers
GROUP BY country
ORDER BY COUNT(DISTINCT customer_key) DESC;

-- Find Total customer by gender 
SELECT COUNT(DISTINCT customer_key) as total_customers,
	   gender
FROM gold.dim_customers 
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category 
SELECT * FROM gold.dim_products;

SELECT category, COUNT(product_key) as total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is average cost in each category
SELECT category, ROUND(AVG(product_cost)) as avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is total revenue generated for each category?
SELECT dp.category,SUM(fs.sales_amount) as total_revenue
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_products As dp 
ON fs.product_key = dp.product_key
GROUP BY dp.category
ORDER BY total_revenue DESC;


-- Total revenue generated by each customer
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) as total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items accross the countries
SELECT 
c.country,
SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;


